feat: add metabase component documentation
ForestAdmin/documentation-user-guide pull request #36
Opened 2024-05-23 09:47 UTC by arnaud-moncel

2024-06-11 14:51 UTC, jeffladiray requested changes

2024-06-11 14:51 UTC, jeffladiray commented on workspaces/building-a-workspace/README.md
> +This is a basic query string based input that can intercact with workspace context.
interact

2024-06-11 14:52 UTC, arnaud-moncel commented on workspaces/building-a-workspace/README.md
> +This is a basic query string based input that can intercact with workspace context.
Oopsy 😅

2024-06-12 07:27 UTC, jeffladiray approved these changes

2024-06-12 07:28 UTC, merged